### PR TITLE
Create a vignette outlining how to extract comparables from LightGBM

### LINKED ISSUE #1: Create function to extract the leaf node assignments of an observation and output comparable observations
# Overview / Context

Our office often gets asked "What properties did you look at to value my property?" or "What are my comparables?" There's not a clear answer to this question since our models effectively look at _all_ available sales when training. However, there may be a way to extract pseudo-comparable observations by leveraging the structure of LightGBM's trees.

When LightGBM is training, it creates decision trees that split the continuous and categorical features into separate leaf nodes. For a single decision tree, it is likely that the observations that share the same terminal leaf nodes are very similar to each other, since they've ended up in the same split. We may be able to extract leaf node assignments and then back those assignments out into a set of comparables, or a similarity score.

The goal of this issue is to create a function that extracts either a set of comparables, a similarity index, or something similar. This will be part 1 of a longer project dedicated to making better tooling around comparables.

## Task

Create a function to extract comparables or a score given a:

- Serialized LightGBM model object
- Parsnip workflow object
- Data frame of sales (training data)
- A vector of observation IDs that require comparables

The function should have a signature something like:

```r
extract_comps <- function(object, workflow, new_data, obs_id) { 
   ...
}
```

It should return a nested list, where each nested item is a list of comparables for the input `obs_id`s.

## Additional Requirements

* The function should include documentation and should be integrated into the larger package.
* Please submit a merge request when ready to close this issue.
* The function should take a _vector_ input of IDs and quickly return an output. Imagine scaling this up to 1M+ IDs.
* Add as few dependencies as possible to the package `DESCRIPTION`. Ideally, add none.

### PR DESCRIPTION
**Pull request by dfsnow**
This PR adds a vignette outlining the process of extracting comparable properties from a LightGBM model using a novel leaf node matching technique. It does _not_ include code updates to the package since the code required for comp finding is short enough to simply be inlined anywhere we would actually use it.

Most of the credit for this goes to our former intern Claire Boyd.

- @ccao-jardine or @wrridgeway, can one of you review the vignette content?
- @jeancochrane Feel free to review content if you're curious / want a break from data eng. stuff.

Since we don't have PR previews setup yet for our package docs, you'll need to download the following zip file, decompress it, then open the HTML doc to view the knit content: [finding-comps.html.zip](https://github.com/ccao-data/lightsnip/files/12232433/finding-comps.html.zip)

The vignette code itself is a mess, but is extremely non-critical, so I'm fine with it.

Closes #1.

### CODE REVIEW

**Comment by wrridgeway** [comment]
**praise (negging):** I love this.

**suggestion (condescending):**

1. Be more explicit about how boolean multiplication works.
2. Perhaps include "i.e." before the variable you use as an example when describing splits `(gr_liv_area)`.

**Review by jeancochrane — DISMISSED** [review]
Super clear and easy to follow, bravo!

**Review by wrridgeway — APPROVED** [review]

**Comment by ccao-jardine** [comment]
This is looking great! I'd like to propose a few slight refinements before publication. Happy to discuss.

The goal is to answer, "What sales did you use to value my property?" The novel contribution is the ability to answer this precise question, and it's important to distinguish "sales used for valuation by the model" from "all comparable properties." CookViewer and SmartFile are way to properties that are merely comparable based on characteristics, regardless of sale status, and it's important to make salient that this is a different method to answer a foundationally different question. To that end...

**General suggestions about conventions used throughout the vignette:**
- [ ]  Replace the term "comparables" with something more precise. Source sales? Input comps? Training comps? (Sale comps is obvious but, because it is already well defined in the appraisal space, might be confusing. Maybe.)
- [ ] Rename ID --> Property ID

**Specific suggestions**
- [ ] at #ames-housing-data-example-decision-tree, let's unpack this kind of diagram even more broadly and remind people that this is about the training set by adding something like: "The below decision tree has learned about how each property variable, like neighborhood and gr_liv_area, contributed to sale prices."
- [ ] For the example, let's unpack Split 0, then Split 2.
- [ ] in Final Results tables, for the second table with IDs not of the target property, can we include sale price? (Ideally for column alignment purposes between the two final results tables, the column would also exist in the table for ID = 2 but be empty.) That table would help clarify that this answers "What sales did you use to value my property?"

**Comment by dfsnow** [comment]
@ccao-jardine You missed the boat on this PR but these are good points. Moved to issue #4.

**Pull request merged**
